require 'coveralls'
Coveralls.wear!
language: node_js
  addons:
    code_climate:
        repo_token: DhrCpnTFVMsuZ7CYVNOK0kursh7cnA5WX
      sudo: false
      node_js:
        - 10
        - 9
        - 8
        - 7
        - 6
      install:
        - cd istanbul-mocha && npm install && cd ..
      script:
        - cd istanbul-mocha && npm test